export const pretVol2Products = [
  {size:'Medium',
    id: 'a1',
    name: "3 Piece - Printed Embroidered Suit - MONOTUNE Vol2",
    slug: "3-piece-printed-embroidered-suit-monotune-vol2",
   color:'Red',
    stock: 5,
    price: 9990,
    discount: 8,
    pieces: 3,
    type: "Printed Embroidered",
    brand: "MONOTUNE",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Vol-2",
    image: ["/cloth1a.png", "/cloth1b.png", "/cloth1c.png", "/cloth1d.png", "/cloth1e.png", "/cloth1f.png"],
    description: "A sophisticated 3-piece ensemble featuring elegant embroidery and vibrant prints, perfect for festive occasions.",
    createdAt: "2025-07-05T10:00:00Z"
  },
  {size:'Medium',
    id: 'a2',
    name: "3 Piece - Printed Suit - MONOTUNE Vol2",
    slug: "3-piece-printed-suit-monotune-vol2",
    color:'Red',
    stock: 5,
    price: 8990,
    discount: 5,
    pieces: 3,
    type: "Printed",
    brand: "MONOTUNE",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Vol-2",
    image: ["/cloth2a.png", "/cloth2b.png", "/cloth2c.png", "/cloth2d.png", "/cloth2e.png", "/cloth2f.png"],
    description: "A stylish and breathable 3-piece printed suit designed for everyday elegance and comfort.",
    createdAt: "2025-07-04T14:00:00Z"
  },
  {size:'Medium',
    id: 'a3',
    name: "2 Piece - Printed Suit - MONOTUNE Vol2",
    slug: "2-piece-printed-suit-monotune-vol2",
    color:'Red',
    stock: 5,
    price: 5490,
    discount: 6,
    pieces: 2,
    type: "Printed",
    brand: "MONOTUNE",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Vol-2",
    image: ["/cloth3a.png", "/cloth3b.png", "/cloth3c.png", "/cloth3d.png", "/cloth3e.png", "/cloth3f.png"],
    description: "Casual and classy, this 2-piece printed suit is ideal for effortless daytime wear.",
    createdAt: "2025-07-03T11:30:00Z"
  },
  {size:'Medium',
    id: 'a4',
    name: "2 Piece - Embroidered Suit - MONOTUNE Vol2",
    slug: "2-piece-embroidered-suit-monotune-vol2",
    color:'Red',
    stock: 5,
    price: 7490,
    discount: 4,
    pieces: 2,
    type: "Embroidered",
    brand: "MONOTUNE",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Vol-2",
    image: ["/cloth4a.png", "/cloth4b.png", "/cloth4c.png", "/cloth4d.png", "/cloth4e.png", "/cloth4f.png"],
    description: "Refined and graceful, this 2-piece embroidered suit adds charm to your semi-formal wardrobe.",
    createdAt: "2025-07-02T16:15:00Z"
  }
];

export const pretPrintedProducts = [
  {size:'Medium',
    id: 'a5',
    name: "2 Piece - Printed Suit - MONOTUNE Printed",
    slug: "2-piece-printed-suit-monotune-printed",
    sku: "PS25-252",
    stock: 5,
    price: 5490,
    color: 'White',
    discount: 7,
    pieces: 2,
    type: "Printed",
    brand: "MONOTUNE",
    category: "Women",
    subcategory: "Printed",
    childCategory: "Printed",
    image: ["/cloth5a.png", "/cloth5b.png", "/cloth5c.png", "/cloth5d.png", "/cloth5e.png"],
    description: "A lightweight 2-piece printed suit offering effortless grace for everyday elegance.",
    createdAt: "2025-07-03T09:45:00Z"
  },
  {size:'Medium',
    id: 'a6',
    name: "3 Piece - Printed Suit - MONOTUNE Printed",
    slug: "3-piece-printed-suit-monotone-printed",
    sku: "PS25-251-PRINTED",
    stock: 0,
    price: 8990,
    discount: 5,
    pieces: 3,
    type: "Printed",
    brand: "MONOTUNE",
    category: "Women",
    subcategory: "Printed",
    childCategory: "Printed",
    image: ["/cloth6a.png", "/cloth6b.png", "/cloth6c.png", "/cloth6d.png", "/cloth6e.png", "/cloth6f.png"],
    description: "A classic 3-piece printed outfit featuring eye-catching designs ideal for festive wear.",
    createdAt: "2025-07-02T17:00:00Z"
  },
  {size:'Medium',
    id: 'a7',
    name: "3 Piece - Printed Suit - BOLD FLORAL Printed",
    slug: "3-piece-printed-suit-bold-floral-printed",
    color:'Red',
    stock: 5,
    price: 9990,
    discount: 9,
    pieces: 3,
    type: "Printed",
    brand: "BOLD FLORAL",
    category: "Women",
    subcategory: "Printed",
    childCategory: "Printed",
    image: ["/cloth7a.png", "/cloth7b.png", "/cloth7c.png", "/cloth7d.png", "/cloth7e.png", "/cloth7f.png"],
    description: "Show-stopping floral prints on a 3-piece ensemble that blends boldness with tradition.",
    createdAt: "2025-07-01T13:00:00Z"
  },
  {size:'Medium',
    id: 'a8',
    name: "SB-40 TABAAN",
    slug: "SB-40_TABAAN",
    color:'Red',
    stock: 5,
    price: 36900,
    discount: 9,
    pieces: 3,
    type: "Unstitched",
    brand: "BOLD FLORAL",
    category: "Women",
    subcategory: "Printed",
    childCategory: "Unstitched",
    image: ["/cloth8a.png", "/cloth8b.png", "/cloth8c.png", "/cloth8d.png", "/cloth8e.png", "/cloth8f.png"],
    description: "Show-stopping floral prints on a 3-piece ensemble that blends boldness with tradition.",
    createdAt: "2025-06-30T15:10:00Z"
  },
  {
    id: 'a9',
    name: "Embroided Organza/Net - A - 5008",
    slug: "Embroided-Organza-Net-A-5008",
   size:'Medium',
    stock: 5,
    price: 32000,
    color: 'Yellow',
    discount: 9,
    pieces: 3,
    type: "Unstitched",
    brand: "BOLD FLORAL",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Unstitched",
    image: ["/cloth9a.png", "/cloth9b.png", "/cloth9c.png", "/cloth9d.png", "/cloth9e.png", "/cloth9f.png"],
    description: "Show-stopping floral prints on a 3-piece ensemble that blends boldness with tradition.",
    createdAt: "2025-06-28T12:20:00Z"
  },
  {
    id: 'a10',
    name: "AF-PS-8002-LUNA",
    slug: "AF-PS-8002-LUNA",
    size:'Medium',
    stock: 5,
    price: 3000,
    discount: 9,
    color: 'Purple',
    pieces: 3,
    type: "Unstitched",
    brand: "BOLD FLORAL",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Unstitched",
    image: ["/cloth10a.png", "/cloth10b.png", "/cloth10c.png", "/cloth10d.png", "/cloth10e.png", "/cloth10f.png"],
    description: "Show-stopping floral prints on a 3-piece ensemble that blends boldness with tradition.",
    createdAt: "2025-06-27T11:05:00Z"
  },
  {
    id: 'a11',
    name: "LUNE",
    slug: "LUNE",
   size:'Medium',
    stock: 5,
    price: 5000,
    discount: 9,
    color: 'Silver',
    pieces: 3,
    type: "Unstitched",
    brand: "BOLD FLORAL",
    category: "Women",
    subcategory: "Pret",
    childCategory: "Unstitched",
    image: ["/cloth11a.png", "/cloth11b.png", "/cloth11c.png", "/cloth11d.png", "/cloth11e.png"],
    description: "Show-stopping floral prints on a 3-piece ensemble that blends boldness with tradition.",
    createdAt: "2025-06-25T10:10:00Z"
  }
];



  export const AllProducts = [...pretPrintedProducts,...pretVol2Products]

  
